name: VH
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.7
  - root=6.24.6
  - pip
  - pip:
    - numpy==1.21.4
    - pandas==1.3.4
    - matplotlib==3.5.0
    - uproot==4.1.8
    - awkward==1.5.1
    - tables==3.6.1
    - seaborn==0.11.2
    - coffea==0.7.11
    - jupyter
    - mplhep
