executable = condor_rHbb.sh
arguments = $(ProcId)
transfer_input_files  = output
output                = rHbb.$(ClusterId).$(ProcId).out
error                 = rHbb.$(ClusterId).$(ProcId).err
log                   = rHbb.$(ClusterId).log

# Send the job to Held state on failure.
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

# Periodically retry the jobs every 10 minutes, up to a maximum of 5 retries.
periodic_release =  (NumJobStarts < 3) && ((CurrentTime - EnteredCurrentStatus) > 600)

+ApptainerImage = "/cvmfs/singularity.opensciencegrid.org/cmssw/cms:rhel7"

queue 10

